default_stages:
  - pre-commit
fail_fast: true
repos:
  - repo: local
    hooks:
      - id: conda-environment
        name: Require the activated Conda and Poetry environment
        entry: python scripts/check_environment.py
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        language: system
      - id: end-of-file-fixer
        language: system
      - id: check-json
        language: system
      - id: check-toml
        language: system
      - id: check-yaml
        language: system
      - id: debug-statements
        language: system
      - id: check-builtin-literals
        language: system
      - id: check-case-conflict
        language: system
      - id: check-docstring-first
        language: system
      - id: detect-private-key
        language: system

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.2"
    hooks:
      - id: prettier
        language: system
        additional_dependencies: []
        entry: npm exec --yes --package=prettier@3.0.2 -- prettier --write --list-different --ignore-unknown

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format
        language: system
        pass_filenames: true
        types:
          - python

      - id: ruff-check
        name: ruff-check
        entry: poetry run ruff check
        language: system
        pass_filenames: true
        types:
          - python

      - id: mypy
        name: mypy
        entry: poetry run mypy src
        files: ^src/freecampus_agents/.*\.py$
        language: system
        pass_filenames: false
        types:
          - python
